export const GET_PROFILE = 'GET_PROFILE'
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const SORT_PRODUCTS = 'SORT_PRODUCTS'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const CLEAR_CART = 'CLEAR_CART'
